"""Twilio primitives (phase 5 groundwork, app/infiltrate/telephony.py).

These are the parts of real telephony that can be proven correct WITHOUT a
Twilio account, which is the point of building them now: signature validation
especially is security-critical and much better settled calmly than under
deadline once credentials exist.

The signature test uses Twilio's own published example rather than a
self-consistency check — a homegrown "sign then verify with the same code"
test passes happily even if the algorithm is wrong in the same way twice.
"""

from contextlib import asynccontextmanager

import pytest

from app.core.config import Settings
from app.infiltrate.telephony import (
    TwilioCallClient,
    build_stream_twiml,
    verify_twilio_signature,
)

# Twilio's documented worked example (Security docs), auth token "12345".
#
# The expected signature below was generated by Twilio's OWN library —
#   RequestValidator("12345").compute_signature(_DOC_URL, _DOC_PARAMS)
# with the `twilio` package installed in a throwaway venv — and our
# implementation reproduces it byte-for-byte. That cross-check is the whole
# value of this test: an expected value written from memory or derived from our
# own code proves nothing about whether the algorithm is right.
_DOC_URL = "https://mycompany.com/myapp.php?foo=1&bar=2"
_DOC_PARAMS = {
    "Digits": "1234",
    "To": "+18005551212",
    "From": "+14158675310",
    "Caller": "+14158675310",
    "CallSid": "CA1234567890ABCDE",
}
_DOC_TOKEN = "12345"
_DOC_SIGNATURE = "GvWf1cFY/Q7PnoempGyD5oXAezc="


def test_signature_matches_twilios_published_example():
    """The canonical vector — proves the algorithm, not just our own symmetry."""
    assert verify_twilio_signature(
        _DOC_TOKEN, _DOC_URL, _DOC_PARAMS, _DOC_SIGNATURE
    ) is True


@pytest.mark.parametrize(
    ("desc", "token", "url", "params", "sig"),
    [
        ("wrong token", "wrong", _DOC_URL, _DOC_PARAMS, _DOC_SIGNATURE),
        ("tampered url", _DOC_TOKEN, _DOC_URL + "&evil=1", _DOC_PARAMS, _DOC_SIGNATURE),
        ("added param", _DOC_TOKEN, _DOC_URL, {**_DOC_PARAMS, "X": "1"}, _DOC_SIGNATURE),
        ("dropped param", _DOC_TOKEN, _DOC_URL, {k: v for k, v in list(_DOC_PARAMS.items())[:-1]}, _DOC_SIGNATURE),
        ("changed value", _DOC_TOKEN, _DOC_URL, {**_DOC_PARAMS, "Digits": "9999"}, _DOC_SIGNATURE),
        ("empty signature", _DOC_TOKEN, _DOC_URL, _DOC_PARAMS, ""),
        ("no token configured", "", _DOC_URL, _DOC_PARAMS, _DOC_SIGNATURE),
    ],
)
def test_signature_rejects_tampering(desc, token, url, params, sig):
    """Every mutation must fail closed. An unconfigured token is NOT a pass —
    otherwise forgetting to set it silently accepts forged webhooks."""
    assert verify_twilio_signature(token, url, params, sig) is False, desc


def test_signature_param_order_does_not_matter():
    """Twilio sorts by name, so dict iteration order must not change the result."""
    reversed_params = dict(reversed(list(_DOC_PARAMS.items())))
    assert verify_twilio_signature(
        _DOC_TOKEN, _DOC_URL, reversed_params, _DOC_SIGNATURE
    ) is True


def test_twiml_opens_a_bidirectional_stream():
    xml = build_stream_twiml("wss://ittu.example/media")
    # <Connect> (not <Start>) — two-way audio, and it holds the call open.
    assert "<Connect>" in xml and '<Stream url="wss://ittu.example/media"/>' in xml
    assert xml.startswith("<?xml")


def test_twiml_escapes_and_includes_a_greeting():
    xml = build_stream_twiml("wss://x.example/m?a=1&b=2", greeting='Halo "Bu" & selamat')
    assert "&amp;" in xml and "&quot;" in xml
    assert "<Say" in xml
    # A raw ampersand would make Twilio reject the document as malformed XML.
    assert "?a=1&b=2" not in xml


@pytest.mark.parametrize("bad", ["https://x.example/m", "ws://x.example/m", "x.example"])
def test_twiml_rejects_non_wss_urls(bad):
    """Twilio won't open a plaintext or non-websocket media stream, and call
    audio is evidence — fail at build time, not silently at call time."""
    with pytest.raises(ValueError):
        build_stream_twiml(bad)


def test_client_fails_loud_without_credentials():
    """Same posture as every other LIVE adapter: never silently degrade."""
    with pytest.raises(NotImplementedError, match="ITTU_TWILIO_ACCOUNT_SID"):
        TwilioCallClient(Settings(twilio_account_sid="", twilio_auth_token=""))
    # A half-configured account is still unusable — both halves are required.
    with pytest.raises(NotImplementedError):
        TwilioCallClient(Settings(twilio_account_sid="AC123", twilio_auth_token=""))


# --- The answer webhook (POST /api/telephony/voice) ---------------------------


def _signed(client, url_base, params, token):
    """POST the webhook with a correctly-computed signature."""
    import base64
    import hashlib
    import hmac

    payload = url_base + "".join(f"{k}{v}" for k, v in sorted(params.items()))
    sig = base64.b64encode(
        hmac.new(token.encode(), payload.encode(), hashlib.sha1).digest()
    ).decode()
    return client.post(
        "/api/telephony/voice", data=params, headers={"X-Twilio-Signature": sig}
    )


@pytest.fixture
def twilio_client():
    """TestClient with Twilio configured and a pinned public base URL."""
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.main import app

    s = get_settings()
    prior = (s.twilio_auth_token, s.public_base_url)
    s.twilio_auth_token = "test-token"
    s.public_base_url = "https://ittu.example"
    try:
        yield TestClient(app), "https://ittu.example/api/telephony/voice", "test-token"
    finally:
        s.twilio_auth_token, s.public_base_url = prior


def test_webhook_accepts_a_correctly_signed_call(twilio_client):
    client, url, token = twilio_client
    r = _signed(client, url, {"CallSid": "CA1", "From": "+62811", "To": "+62822"}, token)
    assert r.status_code == 200
    assert "application/xml" in r.headers["content-type"]
    # Speaks and hangs up — NOT <Connect><Stream>, which would point Twilio at a
    # media bridge that doesn't exist and connect a real caller to silence.
    assert "<Say" in r.text and "<Hangup/>" in r.text
    assert "<Stream" not in r.text


def test_webhook_rejects_forged_and_unsigned_requests(twilio_client):
    client, url, token = twilio_client
    params = {"CallSid": "CA1", "From": "+62811"}

    # No signature header at all.
    assert client.post("/api/telephony/voice", data=params).status_code == 403
    # Signature for DIFFERENT params (replayed from another request).
    stolen = _signed(client, url, {"CallSid": "OTHER"}, token).request.headers[
        "X-Twilio-Signature"
    ]
    r = client.post(
        "/api/telephony/voice", data=params, headers={"X-Twilio-Signature": stolen}
    )
    assert r.status_code == 403
    # Signed with the wrong token (an attacker guessing).
    assert _signed(client, url, params, "wrong-token").status_code == 403


def test_webhook_says_the_line_when_no_live_tts_is_configured(twilio_client):
    """The <Say> branch, stated explicitly rather than relied on by accident.

    ``test_webhook_accepts_a_correctly_signed_call`` above also lands here (the
    suite runs with the default ``browser`` provider), so without this test the
    fallback would be covered only as a side effect of a fixture default.
    """
    from app.core.config import get_settings

    client, url, token = twilio_client
    s = get_settings()
    prior = s.tts_provider
    s.tts_provider = "browser"
    try:
        r = _signed(client, url, {"CallSid": "CA1", "To": "+62822"}, token)
        assert "<Say" in r.text and "<Play>" not in r.text
    finally:
        s.tts_provider = prior


def test_webhook_plays_our_own_voice_when_a_live_tts_provider_is_configured(twilio_client):
    """A persona that sounds like an IVR gives itself away in two seconds, so a
    configured provider must actually change the TwiML."""
    from app.core.config import get_settings

    client, url, token = twilio_client
    s = get_settings()
    prior = (s.tts_provider, s.google_tts_api_key)
    s.tts_provider, s.google_tts_api_key = "google", "test-key"
    try:
        r = _signed(client, url, {"CallSid": "CA1", "To": "+62822"}, token)
        assert r.status_code == 200
        assert "<Play>https://ittu.example/api/telephony/audio/greeting.mp3</Play>" in r.text
        assert "<Say" not in r.text
        assert "<Hangup/>" in r.text
    finally:
        s.tts_provider, s.google_tts_api_key = prior


def test_webhook_falls_back_to_say_when_the_provider_has_no_key(twilio_client):
    """A provider NAME without its key would emit <Play> for audio we cannot
    synthesize — the caller would hear silence, which is worse than a generic
    voice. Knowing the name is not the same as being able to speak."""
    from app.core.config import get_settings

    client, url, token = twilio_client
    s = get_settings()
    prior = (s.tts_provider, s.google_tts_api_key)
    s.tts_provider, s.google_tts_api_key = "google", ""
    try:
        r = _signed(client, url, {"CallSid": "CA1", "To": "+62822"}, token)
        assert "<Say" in r.text and "<Play>" not in r.text
    finally:
        s.tts_provider, s.google_tts_api_key = prior


# --- The conversation loop (POST /api/telephony/gather) ----------------------


@pytest.fixture
def talking_client(monkeypatch):
    """Twilio configured, plus a stub voice and a stub brain.

    Both providers are stubbed rather than reached: a test that needs Google and
    Gemini to be up is a test that fails for reasons that have nothing to do with
    the code under test.
    """
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.infiltrate import router as ir
    from app.infiltrate.voice import TTSResult
    from app.main import app

    spoken: list[str] = []

    class _FakeTTS:
        provider = "google"

        def __init__(self, settings=None):
            pass

        async def synthesize(self, text, voice="persona"):
            spoken.append(text)
            return TTSResult(
                provider="google", voice=voice, text=text, duration_seconds=1.0,
                audio_bytes=b"\xff\xf3fake", mime_type="audio/mpeg",
            )

    class _FakeGateway:
        def __init__(self, settings=None):
            pass

        async def complete(self, messages, tools=None, turn=0, max_tokens=1024):
            from app.infiltrate.gateway import LLMResponse

            heard = messages[-1]["content"]
            return LLMResponse(content=f"jawaban untuk: {heard[:20]}", model="fake")

    monkeypatch.setitem(
        __import__("app.infiltrate.voice", fromlist=["LIVE_TTS_PROVIDERS"]).LIVE_TTS_PROVIDERS,
        "google", _FakeTTS,
    )
    monkeypatch.setattr("app.infiltrate.gateway.LiteLLMGateway", _FakeGateway)

    s = get_settings()
    prior = (s.twilio_auth_token, s.public_base_url, s.tts_provider,
             s.google_tts_api_key, s.llm_api_key)
    s.twilio_auth_token = "test-token"
    s.public_base_url = "https://ittu.example"
    s.tts_provider, s.google_tts_api_key = "google", "test-key"
    s.llm_api_key = "test-llm-key"
    ir._conversations.clear()
    ir._dynamic_audio.clear()
    ir._audio_cache.clear()
    try:
        yield TestClient(app), "https://ittu.example", "test-token", spoken
    finally:
        (s.twilio_auth_token, s.public_base_url, s.tts_provider,
         s.google_tts_api_key, s.llm_api_key) = prior
        ir._conversations.clear()
        ir._dynamic_audio.clear()
        ir._audio_cache.clear()


def _gather(client, base, params, token):
    import base64
    import hashlib
    import hmac

    url = f"{base}/api/telephony/gather"
    payload = url + "".join(f"{k}{v}" for k, v in sorted(params.items()))
    sig = base64.b64encode(
        hmac.new(token.encode(), payload.encode(), hashlib.sha1).digest()
    ).decode()
    return client.post(
        "/api/telephony/gather", data=params, headers={"X-Twilio-Signature": sig}
    )


def test_answering_opens_a_conversation_when_there_is_a_voice_and_a_brain(talking_client):
    """With both, the call must LISTEN. Greeting-then-hangup is a doorbell."""
    client, base, token, _ = talking_client
    r = _signed(client, f"{base}/api/telephony/voice",
                {"CallSid": "CA1", "To": "+18143771198"}, token)
    assert r.status_code == 200
    assert '<Gather input="speech"' in r.text
    assert 'language="id-ID"' in r.text
    assert f"{base}/api/telephony/gather" in r.text
    # The <Redirect> is what catches a caller who says nothing at all.
    assert "<Redirect" in r.text
    assert "<Hangup/>" not in r.text


def test_answering_falls_back_to_one_line_without_a_brain(talking_client):
    """A voice with no LLM must NOT gather: asking a question we cannot answer
    leaves the caller talking into silence."""
    from app.core.config import get_settings

    client, base, token, _ = talking_client
    s = get_settings()
    prior = s.llm_api_key
    s.llm_api_key = ""
    try:
        r = _signed(client, f"{base}/api/telephony/voice",
                    {"CallSid": "CA1", "To": "+1"}, token)
        assert "<Gather" not in r.text
        assert "<Play>" in r.text and "<Hangup/>" in r.text
    finally:
        s.llm_api_key = prior


def test_a_spoken_turn_is_answered_and_the_reply_audio_is_served(talking_client):
    client, base, token, spoken = talking_client
    _signed(client, f"{base}/api/telephony/voice", {"CallSid": "CA9"}, token)
    r = _gather(client, base, {"CallSid": "CA9", "SpeechResult": "halo bu ada investasi"}, token)
    assert r.status_code == 200
    assert '<Gather input="speech"' in r.text  # keeps listening

    import re

    url = re.search(r"<Play>([^<]+)</Play>", r.text).group(1)
    key = url.rsplit("/", 1)[-1].removesuffix(".mp3")
    assert key.startswith("r_"), "reply audio must live under a minted token"

    audio = client.get(f"/api/telephony/audio/{key}.mp3")
    assert audio.status_code == 200
    assert audio.headers["content-type"] == "audio/mpeg"
    # Single-use and unique per call — must not be cached anywhere.
    assert audio.headers["cache-control"] == "no-store"
    assert any("jawaban untuk" in t for t in spoken)


def test_reply_tokens_are_not_guessable_text(talking_client):
    """The whole security model of the audio route: it serves a minted token or a
    fixed line, and NEVER synthesizes text lifted from the URL."""
    client, _, _, spoken = talking_client
    before = len(spoken)
    r = client.get("/api/telephony/audio/r_kalimat-yang-saya-mau.mp3")
    assert r.status_code == 404
    assert len(spoken) == before, "a 404 must not reach the TTS provider"


def test_one_silence_re_prompts_and_two_ends_the_call(talking_client):
    """One silence is a caller thinking; two is a dead line."""
    client, base, token, _ = talking_client
    _signed(client, f"{base}/api/telephony/voice", {"CallSid": "CA7"}, token)
    _gather(client, base, {"CallSid": "CA7", "SpeechResult": "halo"}, token)

    first = _gather(client, base, {"CallSid": "CA7", "SpeechResult": ""}, token)
    assert "<Gather" in first.text and "<Hangup/>" not in first.text

    second = _gather(client, base, {"CallSid": "CA7", "SpeechResult": ""}, token)
    assert "<Hangup/>" in second.text and "<Gather" not in second.text


def test_the_turn_cap_ends_the_call(talking_client):
    """Bounds the LLM spend and how long one caller can hold a worker."""
    from app.infiltrate import router as ir

    client, base, token, _ = talking_client
    _signed(client, f"{base}/api/telephony/voice", {"CallSid": "CA8"}, token)
    _gather(client, base, {"CallSid": "CA8", "SpeechResult": "halo"}, token)
    ir._conversations["CA8"]["turns"] = ir.MAX_TURNS

    r = _gather(client, base, {"CallSid": "CA8", "SpeechResult": "masih ada?"}, token)
    assert "<Hangup/>" in r.text
    assert "CA8" not in ir._conversations, "ended calls must not leak state"


def test_gather_rejects_an_unsigned_callback(talking_client):
    """This endpoint drives an LLM and a TTS provider — an unsigned caller who
    found the URL could run up a bill and fabricate a conversation."""
    client, _, _, spoken = talking_client
    before = len(spoken)
    r = client.post(
        "/api/telephony/gather",
        data={"CallSid": "CA1", "SpeechResult": "halo"},
        headers={"X-Twilio-Signature": "forged"},
    )
    assert r.status_code == 403
    assert len(spoken) == before, "a rejected request must not reach a provider"


def test_conversation_and_audio_stores_are_bounded(talking_client):
    """One entry per inbound call, from the open internet. A honeypot is exactly
    the service someone might call ten thousand times."""
    from app.infiltrate import router as ir

    for i in range(ir.MAX_CONVERSATIONS + 25):
        ir._remember(ir._conversations, f"CA{i}", {"turns": 0, "silences": 0, "messages": []})
    assert len(ir._conversations) == ir.MAX_CONVERSATIONS
    assert "CA0" not in ir._conversations, "eviction must drop the OLDEST"

    for i in range(ir.MAX_DYNAMIC_AUDIO + 25):
        ir._remember(ir._dynamic_audio, f"r_{i}", b"x")
    assert len(ir._dynamic_audio) == ir.MAX_DYNAMIC_AUDIO


def test_a_call_is_not_recorded_without_a_declared_agency(talking_client):
    """No ITTU_TELEPHONY_AGENCY means answer-but-discard, and it must be that
    way round: an inbound call carries no JWT, so there is no identity to scope
    storage to. Guessing one would file a real call under a tenant nobody chose."""
    from app.core.config import get_settings
    from app.infiltrate import router as ir

    client, base, token, _ = talking_client
    s = get_settings()
    prior = s.telephony_agency
    s.telephony_agency = ""
    try:
        r = _signed(client, f"{base}/api/telephony/voice", {"CallSid": "CAx"}, token)
        assert "<Gather" in r.text, "the persona still answers"
        assert ir._conversations.get("CAx", {}).get("session_id") is None
    finally:
        s.telephony_agency = prior


def test_recording_failure_never_drops_the_call(talking_client, monkeypatch):
    """Storage is worth a lot; it is not worth hanging up on a live scammer.
    A repository that blows up must degrade to an unrecorded conversation."""
    from app.core.config import get_settings
    from app.infiltrate import router as ir

    client, base, token, _ = talking_client

    @asynccontextmanager
    async def _broken():
        raise RuntimeError("database is down")
        yield  # pragma: no cover

    monkeypatch.setattr(ir, "_telephony_repo", _broken)
    s = get_settings()
    prior = s.telephony_agency
    s.telephony_agency = "bareskrim"
    try:
        answer = _signed(client, f"{base}/api/telephony/voice", {"CallSid": "CAy"}, token)
        assert "<Gather" in answer.text, "the call is still answered"
        turn = _gather(client, base, {"CallSid": "CAy", "SpeechResult": "halo bu"}, token)
        assert turn.status_code == 200
        assert "<Gather" in turn.text, "and the conversation continues"
    finally:
        s.telephony_agency = prior


# --- The audio route (GET /api/telephony/audio/{line}.mp3) --------------------


def test_audio_route_refuses_a_line_it_does_not_know():
    """The security boundary. This route MUST be unauthenticated — Twilio fetches
    <Play> URLs with no credentials and does not sign media requests — so the
    fixed vocabulary is what stops it being a free public text-to-speech proxy
    billed to our provider account. An unknown key must 404 BEFORE any provider
    call, not synthesize whatever was in the URL."""
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.main import app

    s = get_settings()
    prior = (s.tts_provider, s.google_tts_api_key)
    s.tts_provider, s.google_tts_api_key = "google", "test-key"
    try:
        r = TestClient(app).get("/api/telephony/audio/anything-i-like.mp3")
        assert r.status_code == 404
        # The app wraps HTTPException detail as {"error": {...}} with a request_id.
        assert r.json()["error"]["code"] == "unknown_line"
    finally:
        s.tts_provider, s.google_tts_api_key = prior


def test_audio_route_says_so_when_no_provider_is_configured():
    """503 rather than a silent empty body: Twilio would play the empty body as
    nothing at all, and 'the caller heard silence' is the hardest failure to
    diagnose after the fact."""
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.main import app

    s = get_settings()
    prior = s.tts_provider
    s.tts_provider = "browser"
    try:
        r = TestClient(app).get("/api/telephony/audio/greeting.mp3")
        assert r.status_code == 503
        assert r.json()["error"]["code"] == "tts_unavailable"
    finally:
        s.tts_provider = prior


def test_audio_route_serves_and_then_caches_synthesized_audio(monkeypatch):
    """One provider call per line, not one per call. Twilio holds a live caller
    while it fetches this, and the greeting never changes."""
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.infiltrate import router as infiltrate_router
    from app.infiltrate.voice import TTSResult
    from app.main import app

    calls = {"n": 0}

    class _FakeTTS:
        provider = "google"

        def __init__(self, settings=None):
            pass

        async def synthesize(self, text, voice="persona"):
            calls["n"] += 1
            return TTSResult(
                provider="google", voice=voice, text=text, duration_seconds=1.0,
                audio_bytes=b"\xff\xf3ID3-fake-mp3", mime_type="audio/mpeg",
            )

    monkeypatch.setitem(
        __import__("app.infiltrate.voice", fromlist=["LIVE_TTS_PROVIDERS"]).LIVE_TTS_PROVIDERS,
        "google", _FakeTTS,
    )
    infiltrate_router._audio_cache.clear()

    s = get_settings()
    prior = (s.tts_provider, s.google_tts_api_key)
    s.tts_provider, s.google_tts_api_key = "google", "test-key"
    try:
        client = TestClient(app)
        first = client.get("/api/telephony/audio/greeting.mp3")
        assert first.status_code == 200
        assert first.headers["content-type"] == "audio/mpeg"
        assert first.content == b"\xff\xf3ID3-fake-mp3"

        second = client.get("/api/telephony/audio/greeting.mp3")
        assert second.content == first.content
        assert calls["n"] == 1, "second fetch must come from cache, not the provider"
    finally:
        s.tts_provider, s.google_tts_api_key = prior
        infiltrate_router._audio_cache.clear()


def test_webhook_fails_closed_when_twilio_is_not_configured():
    """No auth token must mean NOTHING is accepted — the endpoint is otherwise
    unauthenticated, so an empty token waving requests through would leave it
    wide open to anyone who learns the URL."""
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.main import app

    s = get_settings()
    prior = (s.twilio_auth_token, s.public_base_url)
    s.twilio_auth_token = ""
    s.public_base_url = "https://ittu.example"
    try:
        client = TestClient(app)
        r = client.post(
            "/api/telephony/voice",
            data={"CallSid": "CA1"},
            headers={"X-Twilio-Signature": "anything"},
        )
        assert r.status_code == 403
    finally:
        s.twilio_auth_token, s.public_base_url = prior


# --- Evidentiary clock -------------------------------------------------------


@pytest.mark.anyio
async def test_a_live_session_is_stamped_with_real_time_not_the_replay_epoch():
    """A record that cannot say WHEN is not evidence.

    The scripted replay keeps the fixed _BASE_TS on purpose — its hashes must
    reproduce byte for byte. A live call is a real event, and stamping it with
    the same fictional July epoch as every seeded fixture meant real calls could
    not even be put in order, let alone dated.
    """
    from datetime import datetime, timedelta, timezone

    from app.infiltrate import service
    from app.infiltrate.repository import _memory_repository
    from app.infiltrate.service import StartSessionRequest, start_session

    repo = _memory_repository()
    before = datetime.now(timezone.utc)
    out = await start_session(
        StartSessionRequest(channel_type="voice", interactive=True),
        channel=None, gateway=None, repo=repo,
    )
    after = datetime.now(timezone.utc)

    assert before <= out.started_at <= after
    assert out.started_at != service._BASE_TS
    # And far from the replay epoch, so a regression to it is unmistakable.
    assert abs(out.started_at - service._BASE_TS) > timedelta(days=1)

    msgs = await repo.get_messages(out.id)
    assert msgs and before <= msgs[0].ts <= after


def test_the_scripted_replay_keeps_its_deterministic_epoch():
    """The other half of the rule: fixture hashes must stay reproducible, so the
    replay path must NOT drift onto the wall clock."""
    from app.infiltrate import service

    assert service._BASE_TS.year == 2026 and service._BASE_TS.month == 7
