"""Twilio primitives (phase 5 groundwork, app/infiltrate/telephony.py).

These are the parts of real telephony that can be proven correct WITHOUT a
Twilio account, which is the point of building them now: signature validation
especially is security-critical and much better settled calmly than under
deadline once credentials exist.

The signature test uses Twilio's own published example rather than a
self-consistency check — a homegrown "sign then verify with the same code"
test passes happily even if the algorithm is wrong in the same way twice.
"""

import pytest

from app.core.config import Settings
from app.infiltrate.telephony import (
    TwilioCallClient,
    build_stream_twiml,
    verify_twilio_signature,
)

# Twilio's documented worked example (Security docs), auth token "12345".
#
# The expected signature below was generated by Twilio's OWN library —
#   RequestValidator("12345").compute_signature(_DOC_URL, _DOC_PARAMS)
# with the `twilio` package installed in a throwaway venv — and our
# implementation reproduces it byte-for-byte. That cross-check is the whole
# value of this test: an expected value written from memory or derived from our
# own code proves nothing about whether the algorithm is right.
_DOC_URL = "https://mycompany.com/myapp.php?foo=1&bar=2"
_DOC_PARAMS = {
    "Digits": "1234",
    "To": "+18005551212",
    "From": "+14158675310",
    "Caller": "+14158675310",
    "CallSid": "CA1234567890ABCDE",
}
_DOC_TOKEN = "12345"
_DOC_SIGNATURE = "GvWf1cFY/Q7PnoempGyD5oXAezc="


def test_signature_matches_twilios_published_example():
    """The canonical vector — proves the algorithm, not just our own symmetry."""
    assert verify_twilio_signature(
        _DOC_TOKEN, _DOC_URL, _DOC_PARAMS, _DOC_SIGNATURE
    ) is True


@pytest.mark.parametrize(
    ("desc", "token", "url", "params", "sig"),
    [
        ("wrong token", "wrong", _DOC_URL, _DOC_PARAMS, _DOC_SIGNATURE),
        ("tampered url", _DOC_TOKEN, _DOC_URL + "&evil=1", _DOC_PARAMS, _DOC_SIGNATURE),
        ("added param", _DOC_TOKEN, _DOC_URL, {**_DOC_PARAMS, "X": "1"}, _DOC_SIGNATURE),
        ("dropped param", _DOC_TOKEN, _DOC_URL, {k: v for k, v in list(_DOC_PARAMS.items())[:-1]}, _DOC_SIGNATURE),
        ("changed value", _DOC_TOKEN, _DOC_URL, {**_DOC_PARAMS, "Digits": "9999"}, _DOC_SIGNATURE),
        ("empty signature", _DOC_TOKEN, _DOC_URL, _DOC_PARAMS, ""),
        ("no token configured", "", _DOC_URL, _DOC_PARAMS, _DOC_SIGNATURE),
    ],
)
def test_signature_rejects_tampering(desc, token, url, params, sig):
    """Every mutation must fail closed. An unconfigured token is NOT a pass —
    otherwise forgetting to set it silently accepts forged webhooks."""
    assert verify_twilio_signature(token, url, params, sig) is False, desc


def test_signature_param_order_does_not_matter():
    """Twilio sorts by name, so dict iteration order must not change the result."""
    reversed_params = dict(reversed(list(_DOC_PARAMS.items())))
    assert verify_twilio_signature(
        _DOC_TOKEN, _DOC_URL, reversed_params, _DOC_SIGNATURE
    ) is True


def test_twiml_opens_a_bidirectional_stream():
    xml = build_stream_twiml("wss://ittu.example/media")
    # <Connect> (not <Start>) — two-way audio, and it holds the call open.
    assert "<Connect>" in xml and '<Stream url="wss://ittu.example/media"/>' in xml
    assert xml.startswith("<?xml")


def test_twiml_escapes_and_includes_a_greeting():
    xml = build_stream_twiml("wss://x.example/m?a=1&b=2", greeting='Halo "Bu" & selamat')
    assert "&amp;" in xml and "&quot;" in xml
    assert "<Say" in xml
    # A raw ampersand would make Twilio reject the document as malformed XML.
    assert "?a=1&b=2" not in xml


@pytest.mark.parametrize("bad", ["https://x.example/m", "ws://x.example/m", "x.example"])
def test_twiml_rejects_non_wss_urls(bad):
    """Twilio won't open a plaintext or non-websocket media stream, and call
    audio is evidence — fail at build time, not silently at call time."""
    with pytest.raises(ValueError):
        build_stream_twiml(bad)


def test_client_fails_loud_without_credentials():
    """Same posture as every other LIVE adapter: never silently degrade."""
    with pytest.raises(NotImplementedError, match="ITTU_TWILIO_ACCOUNT_SID"):
        TwilioCallClient(Settings(twilio_account_sid="", twilio_auth_token=""))
    # A half-configured account is still unusable — both halves are required.
    with pytest.raises(NotImplementedError):
        TwilioCallClient(Settings(twilio_account_sid="AC123", twilio_auth_token=""))


# --- The answer webhook (POST /api/telephony/voice) ---------------------------


def _signed(client, url_base, params, token):
    """POST the webhook with a correctly-computed signature."""
    import base64
    import hashlib
    import hmac

    payload = url_base + "".join(f"{k}{v}" for k, v in sorted(params.items()))
    sig = base64.b64encode(
        hmac.new(token.encode(), payload.encode(), hashlib.sha1).digest()
    ).decode()
    return client.post(
        "/api/telephony/voice", data=params, headers={"X-Twilio-Signature": sig}
    )


@pytest.fixture
def twilio_client():
    """TestClient with Twilio configured and a pinned public base URL."""
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.main import app

    s = get_settings()
    prior = (s.twilio_auth_token, s.public_base_url)
    s.twilio_auth_token = "test-token"
    s.public_base_url = "https://ittu.example"
    try:
        yield TestClient(app), "https://ittu.example/api/telephony/voice", "test-token"
    finally:
        s.twilio_auth_token, s.public_base_url = prior


def test_webhook_accepts_a_correctly_signed_call(twilio_client):
    client, url, token = twilio_client
    r = _signed(client, url, {"CallSid": "CA1", "From": "+62811", "To": "+62822"}, token)
    assert r.status_code == 200
    assert "application/xml" in r.headers["content-type"]
    # Speaks and hangs up — NOT <Connect><Stream>, which would point Twilio at a
    # media bridge that doesn't exist and connect a real caller to silence.
    assert "<Say" in r.text and "<Hangup/>" in r.text
    assert "<Stream" not in r.text


def test_webhook_rejects_forged_and_unsigned_requests(twilio_client):
    client, url, token = twilio_client
    params = {"CallSid": "CA1", "From": "+62811"}

    # No signature header at all.
    assert client.post("/api/telephony/voice", data=params).status_code == 403
    # Signature for DIFFERENT params (replayed from another request).
    stolen = _signed(client, url, {"CallSid": "OTHER"}, token).request.headers[
        "X-Twilio-Signature"
    ]
    r = client.post(
        "/api/telephony/voice", data=params, headers={"X-Twilio-Signature": stolen}
    )
    assert r.status_code == 403
    # Signed with the wrong token (an attacker guessing).
    assert _signed(client, url, params, "wrong-token").status_code == 403


def test_webhook_says_the_line_when_no_live_tts_is_configured(twilio_client):
    """The <Say> branch, stated explicitly rather than relied on by accident.

    ``test_webhook_accepts_a_correctly_signed_call`` above also lands here (the
    suite runs with the default ``browser`` provider), so without this test the
    fallback would be covered only as a side effect of a fixture default.
    """
    from app.core.config import get_settings

    client, url, token = twilio_client
    s = get_settings()
    prior = s.tts_provider
    s.tts_provider = "browser"
    try:
        r = _signed(client, url, {"CallSid": "CA1", "To": "+62822"}, token)
        assert "<Say" in r.text and "<Play>" not in r.text
    finally:
        s.tts_provider = prior


def test_webhook_plays_our_own_voice_when_a_live_tts_provider_is_configured(twilio_client):
    """A persona that sounds like an IVR gives itself away in two seconds, so a
    configured provider must actually change the TwiML."""
    from app.core.config import get_settings

    client, url, token = twilio_client
    s = get_settings()
    prior = (s.tts_provider, s.google_tts_api_key)
    s.tts_provider, s.google_tts_api_key = "google", "test-key"
    try:
        r = _signed(client, url, {"CallSid": "CA1", "To": "+62822"}, token)
        assert r.status_code == 200
        assert "<Play>https://ittu.example/api/telephony/audio/greeting.mp3</Play>" in r.text
        assert "<Say" not in r.text
        assert "<Hangup/>" in r.text
    finally:
        s.tts_provider, s.google_tts_api_key = prior


def test_webhook_falls_back_to_say_when_the_provider_has_no_key(twilio_client):
    """A provider NAME without its key would emit <Play> for audio we cannot
    synthesize — the caller would hear silence, which is worse than a generic
    voice. Knowing the name is not the same as being able to speak."""
    from app.core.config import get_settings

    client, url, token = twilio_client
    s = get_settings()
    prior = (s.tts_provider, s.google_tts_api_key)
    s.tts_provider, s.google_tts_api_key = "google", ""
    try:
        r = _signed(client, url, {"CallSid": "CA1", "To": "+62822"}, token)
        assert "<Say" in r.text and "<Play>" not in r.text
    finally:
        s.tts_provider, s.google_tts_api_key = prior


# --- The audio route (GET /api/telephony/audio/{line}.mp3) --------------------


def test_audio_route_refuses_a_line_it_does_not_know():
    """The security boundary. This route MUST be unauthenticated — Twilio fetches
    <Play> URLs with no credentials and does not sign media requests — so the
    fixed vocabulary is what stops it being a free public text-to-speech proxy
    billed to our provider account. An unknown key must 404 BEFORE any provider
    call, not synthesize whatever was in the URL."""
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.main import app

    s = get_settings()
    prior = (s.tts_provider, s.google_tts_api_key)
    s.tts_provider, s.google_tts_api_key = "google", "test-key"
    try:
        r = TestClient(app).get("/api/telephony/audio/anything-i-like.mp3")
        assert r.status_code == 404
        # The app wraps HTTPException detail as {"error": {...}} with a request_id.
        assert r.json()["error"]["code"] == "unknown_line"
    finally:
        s.tts_provider, s.google_tts_api_key = prior


def test_audio_route_says_so_when_no_provider_is_configured():
    """503 rather than a silent empty body: Twilio would play the empty body as
    nothing at all, and 'the caller heard silence' is the hardest failure to
    diagnose after the fact."""
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.main import app

    s = get_settings()
    prior = s.tts_provider
    s.tts_provider = "browser"
    try:
        r = TestClient(app).get("/api/telephony/audio/greeting.mp3")
        assert r.status_code == 503
        assert r.json()["error"]["code"] == "tts_unavailable"
    finally:
        s.tts_provider = prior


def test_audio_route_serves_and_then_caches_synthesized_audio(monkeypatch):
    """One provider call per line, not one per call. Twilio holds a live caller
    while it fetches this, and the greeting never changes."""
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.infiltrate import router as infiltrate_router
    from app.infiltrate.voice import TTSResult
    from app.main import app

    calls = {"n": 0}

    class _FakeTTS:
        provider = "google"

        def __init__(self, settings=None):
            pass

        async def synthesize(self, text, voice="persona"):
            calls["n"] += 1
            return TTSResult(
                provider="google", voice=voice, text=text, duration_seconds=1.0,
                audio_bytes=b"\xff\xf3ID3-fake-mp3", mime_type="audio/mpeg",
            )

    monkeypatch.setitem(
        __import__("app.infiltrate.voice", fromlist=["LIVE_TTS_PROVIDERS"]).LIVE_TTS_PROVIDERS,
        "google", _FakeTTS,
    )
    infiltrate_router._audio_cache.clear()

    s = get_settings()
    prior = (s.tts_provider, s.google_tts_api_key)
    s.tts_provider, s.google_tts_api_key = "google", "test-key"
    try:
        client = TestClient(app)
        first = client.get("/api/telephony/audio/greeting.mp3")
        assert first.status_code == 200
        assert first.headers["content-type"] == "audio/mpeg"
        assert first.content == b"\xff\xf3ID3-fake-mp3"

        second = client.get("/api/telephony/audio/greeting.mp3")
        assert second.content == first.content
        assert calls["n"] == 1, "second fetch must come from cache, not the provider"
    finally:
        s.tts_provider, s.google_tts_api_key = prior
        infiltrate_router._audio_cache.clear()


def test_webhook_fails_closed_when_twilio_is_not_configured():
    """No auth token must mean NOTHING is accepted — the endpoint is otherwise
    unauthenticated, so an empty token waving requests through would leave it
    wide open to anyone who learns the URL."""
    from fastapi.testclient import TestClient

    from app.core.config import get_settings
    from app.main import app

    s = get_settings()
    prior = (s.twilio_auth_token, s.public_base_url)
    s.twilio_auth_token = ""
    s.public_base_url = "https://ittu.example"
    try:
        client = TestClient(app)
        r = client.post(
            "/api/telephony/voice",
            data={"CallSid": "CA1"},
            headers={"X-Twilio-Signature": "anything"},
        )
        assert r.status_code == 403
    finally:
        s.twilio_auth_token, s.public_base_url = prior
