"""Twilio primitives (phase 5 groundwork, app/infiltrate/telephony.py).

These are the parts of real telephony that can be proven correct WITHOUT a
Twilio account, which is the point of building them now: signature validation
especially is security-critical and much better settled calmly than under
deadline once credentials exist.

The signature test uses Twilio's own published example rather than a
self-consistency check — a homegrown "sign then verify with the same code"
test passes happily even if the algorithm is wrong in the same way twice.
"""

import pytest

from app.core.config import Settings
from app.infiltrate.telephony import (
    TwilioCallClient,
    build_stream_twiml,
    verify_twilio_signature,
)

# Twilio's documented worked example (Security docs), auth token "12345".
#
# The expected signature below was generated by Twilio's OWN library —
#   RequestValidator("12345").compute_signature(_DOC_URL, _DOC_PARAMS)
# with the `twilio` package installed in a throwaway venv — and our
# implementation reproduces it byte-for-byte. That cross-check is the whole
# value of this test: an expected value written from memory or derived from our
# own code proves nothing about whether the algorithm is right.
_DOC_URL = "https://mycompany.com/myapp.php?foo=1&bar=2"
_DOC_PARAMS = {
    "Digits": "1234",
    "To": "+18005551212",
    "From": "+14158675310",
    "Caller": "+14158675310",
    "CallSid": "CA1234567890ABCDE",
}
_DOC_TOKEN = "12345"
_DOC_SIGNATURE = "GvWf1cFY/Q7PnoempGyD5oXAezc="


def test_signature_matches_twilios_published_example():
    """The canonical vector — proves the algorithm, not just our own symmetry."""
    assert verify_twilio_signature(
        _DOC_TOKEN, _DOC_URL, _DOC_PARAMS, _DOC_SIGNATURE
    ) is True


@pytest.mark.parametrize(
    ("desc", "token", "url", "params", "sig"),
    [
        ("wrong token", "wrong", _DOC_URL, _DOC_PARAMS, _DOC_SIGNATURE),
        ("tampered url", _DOC_TOKEN, _DOC_URL + "&evil=1", _DOC_PARAMS, _DOC_SIGNATURE),
        ("added param", _DOC_TOKEN, _DOC_URL, {**_DOC_PARAMS, "X": "1"}, _DOC_SIGNATURE),
        ("dropped param", _DOC_TOKEN, _DOC_URL, {k: v for k, v in list(_DOC_PARAMS.items())[:-1]}, _DOC_SIGNATURE),
        ("changed value", _DOC_TOKEN, _DOC_URL, {**_DOC_PARAMS, "Digits": "9999"}, _DOC_SIGNATURE),
        ("empty signature", _DOC_TOKEN, _DOC_URL, _DOC_PARAMS, ""),
        ("no token configured", "", _DOC_URL, _DOC_PARAMS, _DOC_SIGNATURE),
    ],
)
def test_signature_rejects_tampering(desc, token, url, params, sig):
    """Every mutation must fail closed. An unconfigured token is NOT a pass —
    otherwise forgetting to set it silently accepts forged webhooks."""
    assert verify_twilio_signature(token, url, params, sig) is False, desc


def test_signature_param_order_does_not_matter():
    """Twilio sorts by name, so dict iteration order must not change the result."""
    reversed_params = dict(reversed(list(_DOC_PARAMS.items())))
    assert verify_twilio_signature(
        _DOC_TOKEN, _DOC_URL, reversed_params, _DOC_SIGNATURE
    ) is True


def test_twiml_opens_a_bidirectional_stream():
    xml = build_stream_twiml("wss://ittu.example/media")
    # <Connect> (not <Start>) — two-way audio, and it holds the call open.
    assert "<Connect>" in xml and '<Stream url="wss://ittu.example/media"/>' in xml
    assert xml.startswith("<?xml")


def test_twiml_escapes_and_includes_a_greeting():
    xml = build_stream_twiml("wss://x.example/m?a=1&b=2", greeting='Halo "Bu" & selamat')
    assert "&amp;" in xml and "&quot;" in xml
    assert "<Say" in xml
    # A raw ampersand would make Twilio reject the document as malformed XML.
    assert "?a=1&b=2" not in xml


@pytest.mark.parametrize("bad", ["https://x.example/m", "ws://x.example/m", "x.example"])
def test_twiml_rejects_non_wss_urls(bad):
    """Twilio won't open a plaintext or non-websocket media stream, and call
    audio is evidence — fail at build time, not silently at call time."""
    with pytest.raises(ValueError):
        build_stream_twiml(bad)


def test_client_fails_loud_without_credentials():
    """Same posture as every other LIVE adapter: never silently degrade."""
    with pytest.raises(NotImplementedError, match="ITTU_TWILIO_ACCOUNT_SID"):
        TwilioCallClient(Settings(twilio_account_sid="", twilio_auth_token=""))
    # A half-configured account is still unusable — both halves are required.
    with pytest.raises(NotImplementedError):
        TwilioCallClient(Settings(twilio_account_sid="AC123", twilio_auth_token=""))
